---
# tasks file for docker

- name: Check docker group is present
  group:
    name: docker
    state: present

- name: Add docker group to current user
  user:
    name: "{{ docker_user }}"
    group: docker
    append: yes
